#!/bin/bash
# ============================================================================
# setup-phpmyadmin.sh — Instalador de phpMyAdmin para el Dev Dashboard
# ============================================================================
# Descarga, instala y configura phpMyAdmin en el DocumentRoot del dashboard.
# Idempotente: si ya existe, no reinstala.
#
# Uso:   sudo bash setup-phpmyadmin.sh
# ============================================================================

set -e

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
PMA_DIR="$ROOT_DIR/phpmyadmin"
PMA_VERSION="5.2.3"
PMA_URL="https://files.phpmyadmin.net/phpMyAdmin/${PMA_VERSION}/phpMyAdmin-${PMA_VERSION}-all-languages.zip"
PMA_ZIP="/tmp/phpmyadmin-${PMA_VERSION}.zip"

echo "============================================="
echo "  phpMyAdmin installer for Dev Dashboard"
echo "============================================="
echo ""

# ── Verificar permisos ───────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "[✗] Este script necesita sudo."
    exit 1
fi

# ── Ya instalado? ────────────────────────────────────────────────────────────
if [ -f "$PMA_DIR/config.inc.php" ]; then
    echo "[✓] phpMyAdmin ya está instalado en $PMA_DIR"
    echo "    Para reinstalar: rm -rf $PMA_DIR y volvé a ejecutar."
    exit 0
fi

# ── Dependencias ─────────────────────────────────────────────────────────────
echo "→ Verificando dependencias..."
MISSING=""

if ! command -v unzip &>/dev/null; then
    MISSING="$MISSING unzip"
fi
if ! command -v curl &>/dev/null; then
    MISSING="$MISSING curl"
fi

if [ -n "$MISSING" ]; then
    echo "[!] Instalando dependencias:$MISSING"
    if command -v apt &>/dev/null; then
        apt update -qq && apt install -y -qq $MISSING
    elif command -v dnf &>/dev/null; then
        dnf install -y -q $MISSING
    elif command -v pacman &>/dev/null; then
        pacman -S --noconfirm $MISSING
    elif command -v zypper &>/dev/null; then
        zypper install -y $MISSING
    fi
fi
echo "[✓] Dependencias listas"

# ── Descargar ─────────────────────────────────────────────────────────────────
echo "→ Descargando phpMyAdmin ${PMA_VERSION}..."
if [ -f "$PMA_ZIP" ]; then
    echo "    (usando archivo existente en $PMA_ZIP)"
else
    if ! curl -fSL --connect-timeout 30 --max-time 300 -o "$PMA_ZIP" "$PMA_URL"; then
        echo "[✗] Error al descargar phpMyAdmin. Verificá tu conexión o la URL."
        exit 1
    fi
fi
echo "[✓] Descarga completa"

# ── Extraer ───────────────────────────────────────────────────────────────────
echo "→ Extrayendo..."
mkdir -p "$PMA_DIR"
unzip -qo "$PMA_ZIP" -d /tmp/pma-extract/
mv /tmp/pma-extract/phpMyAdmin-${PMA_VERSION}-all-languages/* "$PMA_DIR/"
rm -rf /tmp/pma-extract/
echo "[✓] Extraído en $PMA_DIR"

# ── Configurar ────────────────────────────────────────────────────────────────
echo "→ Configurando..."

# Generar blowfish secret aleatorio
BLOWFISH_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)

cat > "$PMA_DIR/config.inc.php" <<PHPMYADMIN
<?php
/**
 * phpMyAdmin configuration for Dev Dashboard.
 * Auto-generated by setup-phpmyadmin.sh
 */
declare(strict_types=1);

\$cfg['blowfish_secret'] = '${BLOWFISH_SECRET}';
\$cfg['Servers'][1]['auth_type']       = 'cookie';
\$cfg['Servers'][1]['host']            = 'localhost';
\$cfg['Servers'][1]['port']            = '3306';
\$cfg['Servers'][1]['compress']        = false;
\$cfg['Servers'][1]['AllowNoPassword'] = false;
\$cfg['UploadDir']   = '';
\$cfg['SaveDir']     = '';
\$cfg['TempDir']     = '/tmp';
\$cfg['LoginCookieValidity'] = 14400;
\$cfg['MaxRows']     = 100;
\$cfg['SendErrorReports'] = 'never';
PHPMYADMIN

echo "[✓] config.inc.php creado"

# ── Permisos ──────────────────────────────────────────────────────────────────
chown -R "$(stat -c '%U' "$ROOT_DIR"):www-data" "$PMA_DIR" 2>/dev/null || \
    chown -R "$(stat -f '%Su' "$ROOT_DIR" 2>/dev/null):www-data" "$PMA_DIR" 2>/dev/null || \
    chown -R root:www-data "$PMA_DIR"
chmod -R 755 "$PMA_DIR"

echo "[✓] Permisos aplicados"

# ── Verificar Apache ──────────────────────────────────────────────────────────
if command -v apache2ctl &>/dev/null || command -v httpd &>/dev/null; then
    if command -v systemctl &>/dev/null; then
        systemctl reload apache2 2>/dev/null || systemctl reload httpd 2>/dev/null || true
    fi
    echo "[✓] Apache recargado"
fi

# ── Limpiar ───────────────────────────────────────────────────────────────────
rm -f "$PMA_ZIP"

echo ""
echo "============================================="
echo "  ✅ phpMyAdmin ${PMA_VERSION} instalado"
echo "============================================="
echo ""
echo "  URL:      http://localhost/phpmyadmin/"
echo "  Dir:      $PMA_DIR"
echo ""
echo "  El botón en el dashboard se activa automáticamente."
echo "  Si no aparece, reiniciá Apache y recargá la página."
echo ""
